config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs

   root 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parementers, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up).push :first_name, :last_name, :phone
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find params[:id]
  end

  def create
    @blog = Blog.create params[:id]
    redirect_to root_path
  end


  def edit
    @blog = Blog.find params[:id]
  end

  def update
    @blog = Blog.find params[:id]
    @blog.update
    redirect_to root_path
  end


  # def destroy
  #   @blog = Blog.find params[:id]
  #   title = @blog.title
  #   @blog.destroy
  #   if @blog.destroy
  #     flash[:notice] = "\"#{title}\" was deleted succesfully."
  #     redirect_to root_path
  #   else
  #     flash[:error] = "There was an error deleting the topic."
  #     render :show
  #   end
  # end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  

  def index
    @blogs = Blog.all

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1> Edit This Blog</h1>

<%= form_for @blog do |f| %>
    <pre>
    Subject: <%= f.text_field :title %>
    Body: <%= f.text_area :body %>

    <%= f.submit %>
    </pre>  
  <% end %>

app/views/blogs/index.html.erb
<h1>Test View</h1>

app/views/blogs/new.html.erb
<h1> Welcome to the New Blog Page </h1>

<%= form_for @blog do |f| %>
    <pre>
    Subject: <%= f.text_field :title %>
    Body: <%= f.text_area :body %>

    <%= f.submit %>
    </pre>  
  <% end %>

app/views/blogs/show.html.erb
<h1> Show Blog Page </h1>

<%= @blog.title %>
<%= @blog.body %>

  <%= link_to "Edit", edit_blog_path(@blog), class:"button [secondary success alert]" %>

app/views/home/index.html.erb
  <div class="row">
    <div class="large-12 columns">
      <div class="nav-bar right">
       <ul class="button-group">

        <% (@blogs).each do |blog| %>
         <li><%= link_to blog.title%></li>
        
         <% end %>

        </ul>
      </div>
      <h1>Superrr Blog <small>by Doug Walter</small></h1>
      <hr/>
    </div>
  </div>
 
   <%= link_to "New Blog", new_blog_path, class:"button [secondary success alert]" %>
 
 
   
 
  <div class="row">
 
     
    <div class="large-9 medium-8 columns" role="content">
 
      <article>
        <% (@blogs).each do |blog| %>
        <h3><%= link_to blog.title %></h3>
        <h6>Written by <a href="#">Douglas Walter</a> <%= blog.created_at %> </h6>
 
        <div class="row">
          <div class="large-6 columns">
            <p>blog.body</p>
            <% end %>
          </div>
          <div class="large-6 columns">
            <img src="http://placehold.it/400x240&text=[img]"/>
          </div>
        </div>
 
      </article>
 
      <hr/>
 
 
    </div>
  </div>
 

 
  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>Built with Rails 4 by Douglas Walter</p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
  <%= render partial: 'partials/nav' %>
<body>

<% if notice%>
<p class="notice alert-box info radius"><%= notice%></p>
<% elsif alert%>
<p class="alert alert-box info radius"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/partials/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%=link_to 'Home', root_path %></h1>
    </li>

  </ul>


 <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active">
        <% if current_user %>
            <%= link_to 'Log Out', destroy_user_session_path, method: 'DELETE' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path%>
            <li class="active">
            <%= link_to 'Sign Up', user_registration_path, method: 'POST' %>
      </li>
          <% end %>
      </li>


    </ul>
</nav>